# Generated by Django 3.1.6 on 2021-02-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numbers',
            options={'verbose_name_plural': 'Numbers'},
        ),
        migrations.AddField(
            model_name='numbers',
            name='pic',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
